### ISSUE TITLE
internal/modules/cjs/loader.js:582     

### ISSUE THREAD

**Issue by Man-ingo** [DanielMcSheehy/BinanceMarketWatch#1]
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'isomorphic-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by DanielMcSheehy** [comment]
@Amufani have you tried `npm -i isomorphic-fetch`?
